apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: awsme
      role: backend
  template:
    metadata:
      name: backend
      labels:
        app: awsme
        role: backend
    spec:
      initContainers:
      - name: init-db
        image: altorosbarrywilliams/aws-sample-app:1.0.0
        command: ["sh", "-c", "app -run-migrations -port=8080 -db-host=db -db-password=$MYSQL_ROOT_PASSWORD" ]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
      containers:
      - name: backend
        image: altorosbarrywilliams/aws-sample-app:1.0.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        command: ["sh", "-c", "app -mode=backend -run-migrations -port=8080 -db-host=db -db-password=$MYSQL_ROOT_PASSWORD" ]
        ports:
        - name: backend
          containerPort: 8080
