kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    app: awsme
    role: backend
spec:
  containers:
  - name: backend
    image: altorosbarrywilliams/aws-sample-app:1.0.0
    command: ["sh", "-c", "app -mode=backend -run-migrations -port=8080 -db-host=db -db-password=very-secret-password" ]
    ports:
    - name: backend
      containerPort: 8080
